services:
  cart-nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: unless-stopped
    expose:
      - ${APP_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - cart-web-app-network

  cart-nextjs-caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - cart-nextjs-app
    build:
      context: .
      dockerfile: Dockerfile.caddy
    expose:
      - ${CADDY_SERVER_PORT}
    networks:
      - cart-web-app-network

networks:
  cart-web-app-network:
    driver: bridge
