# Use the official Nginx image
FROM nginx:stable-alpine

# Copy your custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# The base Nginx image already has a CMD, so don't need to specify one